# A simple make file with only a clean target.
#

YAJOGLB_LIB = YAJOGLB

default:
	@echo "You must use on of the operating system specific makefiles"

clean:
	$(RM) *.o $(YAJOGLB_LIB) $(YAJOGLB_LIB).a $(YAJOGLB_LIB).1 $(YAJOGLB_LIB).1.1