
# Configurations for the entire project
# The Java compiler to use.
JAVAC               = javac
# Where the Java libraries live.
JLIB                = /usr/lib/jdk1.1/lib/classes.zip
# How to break out directories.
DIR_SEPARATOR       = "/"
# How to break out class paths.
CLASSPATH_SEPARATOR = ":"
# Where all of the JNI headers live.
JNI_GENERIC_HEADERS  = -I/usr/lib/jdk1.1/include
# Where the JNI headers for this platform live.
JNI_SPECIFIC_HEADERS = -I/usr/lib/jdk1.1/include/genunix
# Where the OpenGL headers live.
GL_INCLUDES = -I/usr/local/include -I/usr/i486-linuxlibc1/include/


