# $Id: Makefile.common,v 1.2 1999/04/29 01:22:39 razeh Exp $
# Some common rules that are shared by all of our makefiles, across
# all of our platforms.

OPTIMIZATIONFLAG = -g
JAVAH         = javah
SUFFIXES     += .class .java
COMPILE.java  = $(JAVAC) $(JFLAGS) 
%.class: %.java
	$(COMPILE.java) $<

